version = 0.1

[default.deploy.parameters]
stack_name = "sam-app-v1"
resolve_s3 = true
s3_prefix = "sam-app-v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
