name: Deploy SAM Application

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Build SAM application
      run: sam build
    
    - name: Deploy SAM application
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
    
    - name: Deploy Learning Path API
      run: |
        cd v1-lp
        sam build
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset