name: Deploy Angular Frontend

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET: skill-management-portal-prod-ro0qg44w

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to S3
      run: |
        # Upload all files except index.html with long cache
        aws s3 sync build/ s3://$S3_BUCKET/ \
          --exclude "index.html" \
          --cache-control "public, max-age=31536000" \
          --delete
        
        # Upload index.html with no-cache
        aws s3 cp build/index.html s3://$S3_BUCKET/ \
          --cache-control "no-cache, no-store, must-revalidate"
    
    - name: Invalidate CloudFront
      run: |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?Origins.Items[0].DomainName=='$S3_BUCKET.s3.amazonaws.com'].Id" \
          --output text)
        
        if [ -n "$DISTRIBUTION_ID" ]; then
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
        fi